/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/a-windy-day-fb78f4cc938144e6902dd5cff354d525
title: A Windy Day
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/modelDraco.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <group name="Object_2" scale={0}>
              <group>
                <points geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
                <points geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
                <points geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
                <points geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
                <points geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
                <points geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
                <points geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
                <points geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
                <points geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
                <points geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
                <points geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
                <points geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
                <points geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
                <points geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
                <points geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
                <points geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
                <points geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
                <points geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
                <points geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
                <points geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
                <points geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
                <points geometry={nodes.Object_55.geometry} material={nodes.Object_55.material} />
                <points geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
                <points geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
                <points geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
                <points geometry={nodes.Object_65.geometry} material={nodes.Object_65.material} />
                <points geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
                <points geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
                <points geometry={nodes.Object_71.geometry} material={nodes.Object_71.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
                <points geometry={nodes.Object_75.geometry} material={nodes.Object_75.material} />
                <points geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_79.geometry} material={nodes.Object_79.material} />
                <points geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
                <points geometry={nodes.Object_81.geometry} material={nodes.Object_81.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
                <points geometry={nodes.Object_85.geometry} material={nodes.Object_85.material} />
                <points geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_89.geometry} material={nodes.Object_89.material} />
                <points geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
                <points geometry={nodes.Object_91.geometry} material={nodes.Object_91.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
                <points geometry={nodes.Object_95.geometry} material={nodes.Object_95.material} />
                <points geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_99.geometry} material={nodes.Object_99.material} />
                <points geometry={nodes.Object_100.geometry} material={nodes.Object_100.material} />
                <points geometry={nodes.Object_101.geometry} material={nodes.Object_101.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_104.geometry} material={nodes.Object_104.material} />
                <points geometry={nodes.Object_105.geometry} material={nodes.Object_105.material} />
                <points geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_109.geometry} material={nodes.Object_109.material} />
                <points geometry={nodes.Object_110.geometry} material={nodes.Object_110.material} />
                <points geometry={nodes.Object_111.geometry} material={nodes.Object_111.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_114.geometry} material={nodes.Object_114.material} />
                <points geometry={nodes.Object_115.geometry} material={nodes.Object_115.material} />
                <points geometry={nodes.Object_116.geometry} material={nodes.Object_116.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_119.geometry} material={nodes.Object_119.material} />
                <points geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
                <points geometry={nodes.Object_121.geometry} material={nodes.Object_121.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
                <points geometry={nodes.Object_125.geometry} material={nodes.Object_125.material} />
                <points geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_129.geometry} material={nodes.Object_129.material} />
                <points geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
                <points geometry={nodes.Object_131.geometry} material={nodes.Object_131.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
                <points geometry={nodes.Object_135.geometry} material={nodes.Object_135.material} />
                <points geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_139.geometry} material={nodes.Object_139.material} />
                <points geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
                <points geometry={nodes.Object_141.geometry} material={nodes.Object_141.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
                <points geometry={nodes.Object_145.geometry} material={nodes.Object_145.material} />
                <points geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_149.geometry} material={nodes.Object_149.material} />
                <points geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
                <points geometry={nodes.Object_151.geometry} material={nodes.Object_151.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
                <points geometry={nodes.Object_155.geometry} material={nodes.Object_155.material} />
                <points geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_159.geometry} material={nodes.Object_159.material} />
                <points geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
                <points geometry={nodes.Object_161.geometry} material={nodes.Object_161.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
                <points geometry={nodes.Object_165.geometry} material={nodes.Object_165.material} />
                <points geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_169.geometry} material={nodes.Object_169.material} />
                <points geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
                <points geometry={nodes.Object_171.geometry} material={nodes.Object_171.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
                <points geometry={nodes.Object_175.geometry} material={nodes.Object_175.material} />
                <points geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_179.geometry} material={nodes.Object_179.material} />
                <points geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
                <points geometry={nodes.Object_181.geometry} material={nodes.Object_181.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
                <points geometry={nodes.Object_185.geometry} material={nodes.Object_185.material} />
                <points geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_189.geometry} material={nodes.Object_189.material} />
                <points geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
                <points geometry={nodes.Object_191.geometry} material={nodes.Object_191.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
                <points geometry={nodes.Object_195.geometry} material={nodes.Object_195.material} />
                <points geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_199.geometry} material={nodes.Object_199.material} />
                <points geometry={nodes.Object_200.geometry} material={nodes.Object_200.material} />
                <points geometry={nodes.Object_201.geometry} material={nodes.Object_201.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_204.geometry} material={nodes.Object_204.material} />
                <points geometry={nodes.Object_205.geometry} material={nodes.Object_205.material} />
                <points geometry={nodes.Object_206.geometry} material={nodes.Object_206.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_209.geometry} material={nodes.Object_209.material} />
                <points geometry={nodes.Object_210.geometry} material={nodes.Object_210.material} />
                <points geometry={nodes.Object_211.geometry} material={nodes.Object_211.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_214.geometry} material={nodes.Object_214.material} />
                <points geometry={nodes.Object_215.geometry} material={nodes.Object_215.material} />
                <points geometry={nodes.Object_216.geometry} material={nodes.Object_216.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_219.geometry} material={nodes.Object_219.material} />
                <points geometry={nodes.Object_220.geometry} material={nodes.Object_220.material} />
                <points geometry={nodes.Object_221.geometry} material={nodes.Object_221.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_224.geometry} material={nodes.Object_224.material} />
                <points geometry={nodes.Object_225.geometry} material={nodes.Object_225.material} />
                <points geometry={nodes.Object_226.geometry} material={nodes.Object_226.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_229.geometry} material={nodes.Object_229.material} />
                <points geometry={nodes.Object_230.geometry} material={nodes.Object_230.material} />
                <points geometry={nodes.Object_231.geometry} material={nodes.Object_231.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_234.geometry} material={nodes.Object_234.material} />
                <points geometry={nodes.Object_235.geometry} material={nodes.Object_235.material} />
                <points geometry={nodes.Object_236.geometry} material={nodes.Object_236.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_239.geometry} material={nodes.Object_239.material} />
                <points geometry={nodes.Object_240.geometry} material={nodes.Object_240.material} />
                <points geometry={nodes.Object_241.geometry} material={nodes.Object_241.material} />
              </group>
            </group>
            <group scale={0}>
              <group>
                <points geometry={nodes.Object_244.geometry} material={nodes.Object_244.material} />
                <points geometry={nodes.Object_245.geometry} material={nodes.Object_245.material} />
                <points geometry={nodes.Object_246.geometry} material={nodes.Object_246.material} />
              </group>
            </group>
            <group>
              <group>
                <points geometry={nodes.Object_249.geometry} material={nodes.Object_249.material} />
                <points geometry={nodes.Object_250.geometry} material={nodes.Object_250.material} />
                <points geometry={nodes.Object_251.geometry} material={nodes.Object_251.material} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modelDraco.gltf')
